Update file: src/app/components/screens/WarehouseReceiving.tsx

Apply all changes below exactly.

1) Replace/import block updates:
- In lucide-react import, add `Download`
- Add:
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

Use this import section:

import {
  ScanBarcode,
  Camera,
  CheckCircle,
  Package,
  Plus,
  Trash2,
  SendHorizonal,
  RefreshCw,
  Download,
} from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

2) Inside `export function WarehouseReceiving() {` add supplier states near other useState:
const [supplierName, setSupplierName] = useState("");
const [supplierContact, setSupplierContact] = useState("");
const [supplierAddress, setSupplierAddress] = useState("");

3) Inside the same component, before `return (...)`, add this PDF logic:

const loadImage = (src: string): Promise<HTMLImageElement | null> =>
  new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = src;
  });

const handleDownloadGrn = useCallback(async () => {
  const validLines = lines.filter(
    (line) =>
      line.productId &&
      line.qtyExpected !== "" &&
      line.qtyReceived !== "",
  );

  if (validLines.length === 0) {
    toast.error("No GRN line items to export");
    return;
  }

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const logo = await loadImage("/logo.png");

  if (logo) {
    doc.addImage(logo, "PNG", 40, 30, 56, 56);
  }

  const grnNo = savedGrnNumber ?? `GRN-${receivedDate.replace(/-/g, "")}`;

  doc.setFontSize(16);
  doc.text("GOODS RECEIPT NOTE (GRN)", 110, 50);

  doc.setFontSize(10);
  doc.text(`GRN No: ${grnNo}`, 110, 70);
  doc.text(`Received Date: ${receivedDate}`, 110, 86);

  doc.setFontSize(11);
  doc.text("Supplier Information", 40, 120);
  doc.setFontSize(10);
  doc.text(`Name: ${supplierName || "N/A"}`, 40, 140);
  doc.text(`Contact: ${supplierContact || "N/A"}`, 40, 156);
  doc.text(`Address: ${supplierAddress || "N/A"}`, 40, 172);

  const bodyRows = validLines.map((line, idx) => {
    const item = inventory.find((i) => i.id === line.productId);
    const expected = Number(line.qtyExpected);
    const received = Number(line.qtyReceived);
    const variance = received - expected;

    return [
      String(idx + 1),
      item?.sku ?? "-",
      item?.name ?? "-",
      String(expected),
      String(received),
      String(variance),
    ];
  });

  autoTable(doc, {
    startY: 192,
    head: [["#", "SKU", "Product", "Qty Expected", "Qty Received", "Variance"]],
    body: bodyRows,
    theme: "grid",
    headStyles: { fillColor: [0, 163, 173] },
    styles: { fontSize: 9, cellPadding: 6 },
  });

  const finalY = (doc as any).lastAutoTable?.finalY ?? 220;

  doc.setFontSize(10);
  doc.text(`Notes: ${notes || "-"}`, 40, finalY + 24);
  doc.text("Generated by Pharma Distribution Management System", 40, finalY + 40);
  doc.text("Page 1", pageWidth - 60, pageHeight - 24);

  doc.save(`${grnNo}.pdf`);
}, [
  lines,
  inventory,
  notes,
  receivedDate,
  savedGrnNumber,
  supplierName,
  supplierContact,
  supplierAddress,
]);

4) In the GRN Header CardContent section, replace content with this (keeps existing fields + adds supplier):

<CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
  <div>
    <Label className="text-[#6B7280]">Received Date</Label>
    <Input
      type="date"
      value={receivedDate}
      onChange={(e) => setReceivedDate(e.target.value)}
      className="mt-2 border-[#111827]/10"
      disabled={isPosted}
    />
  </div>

  <div>
    <Label className="text-[#6B7280]">Supplier Name</Label>
    <Input
      value={supplierName}
      onChange={(e) => setSupplierName(e.target.value)}
      placeholder="Enter supplier name"
      className="mt-2 border-[#111827]/10"
      disabled={isPosted}
    />
  </div>

  <div>
    <Label className="text-[#6B7280]">Supplier Contact</Label>
    <Input
      value={supplierContact}
      onChange={(e) => setSupplierContact(e.target.value)}
      placeholder="Phone or email"
      className="mt-2 border-[#111827]/10"
      disabled={isPosted}
    />
  </div>

  <div>
    <Label className="text-[#6B7280]">Notes (Optional)</Label>
    <Input
      value={notes}
      onChange={(e) => setNotes(e.target.value)}
      placeholder="Supplier delivery note, issue summary, etc."
      className="mt-2 border-[#111827]/10"
      disabled={isPosted}
    />
  </div>

  <div className="md:col-span-2">
    <Label className="text-[#6B7280]">Supplier Address</Label>
    <Input
      value={supplierAddress}
      onChange={(e) => setSupplierAddress(e.target.value)}
      placeholder="Supplier address"
      className="mt-2 border-[#111827]/10"
      disabled={isPosted}
    />
  </div>
</CardContent>

5) In sticky action buttons (when not posted), replace the 2-button grid with 3 buttons including Download:

<div className="grid grid-cols-1 md:grid-cols-3 gap-2">
  <Button
    onClick={handleSaveGrn}
    disabled={isSaving || isPosting}
    variant="outline"
    className="h-14 border-[#00A3AD] text-[#00A3AD] hover:bg-[#00A3AD]/10 font-semibold disabled:opacity-50"
  >
    <CheckCircle className="w-5 h-5 mr-2" />
    {isSaving ? "Saving..." : "Save GRN"}
  </Button>

  <Button
    onClick={handlePostGrn}
    disabled={isSaving || isPosting}
    className="h-14 bg-[#059669] hover:bg-[#047857] text-white shadow-lg font-semibold disabled:opacity-50"
  >
    <SendHorizonal className="w-5 h-5 mr-2" />
    {isPosting ? "Posting..." : "Post GRN"}
  </Button>

  <Button
    onClick={handleDownloadGrn}
    disabled={isSaving || isPosting}
    variant="outline"
    className="h-14 border-[#111827]/20 text-[#111827] hover:bg-[#111827]/5 font-semibold"
  >
    <Download className="w-5 h-5 mr-2" />
    Download GRN
  </Button>
</div>

6) Install dependency:
npm i jspdf jspdf-autotable

7) Ensure logo exists at:
public/logo.png
(used by PDF export)
