/**
 * PO Number Generation Service
 * Handles generation and validation of Purchase Order numbers
 */

class PONumberGenerationService {
  constructor() {
    this.sequence = 0;
    this.generatedNumbers = new Set();
    this.dateFormat = 'YYYY-MM-DD';
  }

  /**
   * Generate sequential PO number (e.g., PO-000001, PO-000002)
   */
  generateSequential() {
    this.sequence++;
    const padded = String(this.sequence).padStart(6, '0');
    const poNumber = `PO-${padded}`;

    if (this.generatedNumbers.has(poNumber)) {
      return this.generateSequential(); // Recursive retry if duplicate
    }

    this.generatedNumbers.add(poNumber);
    return poNumber;
  }

  /**
   * Generate date-based PO number (e.g., PO-2026-04-29-001)
   */
  generateDateBased(date = new Date()) {
    if (!(date instanceof Date)) {
      throw new Error('Date must be a valid Date object');
    }

    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');

    // Find next sequence for this day
    let sequence = 1;
    let poNumber = `PO-${year}-${month}-${day}-${String(sequence).padStart(3, '0')}`;

    while (this.generatedNumbers.has(poNumber)) {
      sequence++;
      poNumber = `PO-${year}-${month}-${day}-${String(sequence).padStart(3, '0')}`;
    }

    this.generatedNumbers.add(poNumber);
    return poNumber;
  }

  /**
   * Generate supplier-based PO number (e.g., PO-SUP001-2026-001)
   */
  generateSupplierBased(supplierId, date = new Date()) {
    if (!supplierId) {
      throw new Error('Supplier ID is required');
    }

    if (!(date instanceof Date)) {
      throw new Error('Date must be a valid Date object');
    }

    const year = date.getFullYear();
    const cleanSupplierId = String(supplierId).toUpperCase().substring(0, 6);

    let sequence = 1;
    let poNumber = `PO-${cleanSupplierId}-${year}-${String(sequence).padStart(3, '0')}`;

    while (this.generatedNumbers.has(poNumber)) {
      sequence++;
      poNumber = `PO-${cleanSupplierId}-${year}-${String(sequence).padStart(3, '0')}`;
    }

    this.generatedNumbers.add(poNumber);
    return poNumber;
  }

  /**
   * Generate with checksum (PO-XXXXX-C where C is checksum)
   */
  generateWithChecksum() {
    const baseNumber = this.generateSequential();
    const checksum = this.calculateChecksum(baseNumber);
    return `${baseNumber}-${checksum}`;
  }

  /**
   * Calculate checksum using Luhn algorithm variant
   */
  calculateChecksum(poNumber) {
    if (!poNumber) {
      throw new Error('PO number is required');
    }

    const digits = poNumber.replace(/[^0-9]/g, '');
    let sum = 0;

    for (let i = 0; i < digits.length; i++) {
      const digit = parseInt(digits[i]);
      const multiplied = (i % 2 === 0) ? digit * 2 : digit;
      sum += (multiplied > 9) ? multiplied - 9 : multiplied;
    }

    return (10 - (sum % 10)) % 10;
  }

  /**
   * Validate PO number format
   */
  validatePONumber(poNumber) {
    if (!poNumber || typeof poNumber !== 'string') {
      return {
        valid: false,
        errors: ['PO number must be a non-empty string']
      };
    }

    const errors = [];

    // Check if starts with PO-
    if (!poNumber.startsWith('PO-')) {
      errors.push('PO number must start with PO-');
    }

    // Check minimum length
    if (poNumber.length < 8) {
      errors.push('PO number is too short');
    }

    // Check for valid characters
    if (!/^PO-[A-Z0-9\-]+$/.test(poNumber)) {
      errors.push('PO number contains invalid characters');
    }

    return {
      valid: errors.length === 0,
      errors
    };
  }

  /**
   * Check if PO number was generated by this service
   */
  isGenerated(poNumber) {
    return this.generatedNumbers.has(poNumber);
  }

  /**
   * Get total PO numbers generated
   */
  getTotalGenerated() {
    return this.generatedNumbers.size;
  }

  /**
   * Reset the service (clear all generated numbers)
   */
  reset() {
    this.sequence = 0;
    this.generatedNumbers.clear();
  }

  /**
   * Extract date from date-based PO number
   */
  extractDateFromPO(poNumber) {
    if (!poNumber) {
      throw new Error('PO number is required');
    }

    // Match pattern: PO-YYYY-MM-DD-XXX
    const dateMatch = poNumber.match(/PO-(\d{4})-(\d{2})-(\d{2})-/);

    if (!dateMatch) {
      throw new Error('PO number does not contain date information');
    }

    const [, year, month, day] = dateMatch;
    const date = new Date(parseInt(year), parseInt(month) - 1, parseInt(day));

    if (isNaN(date.getTime())) {
      throw new Error('Invalid date extracted from PO number');
    }

    return date;
  }

  /**
   * Extract supplier ID from supplier-based PO number
   */
  extractSupplierIdFromPO(poNumber) {
    if (!poNumber) {
      throw new Error('PO number is required');
    }

    // Match pattern: PO-XXXXX-YYYY-XXX
    const supplierMatch = poNumber.match(/PO-([A-Z0-9]+)-(\d{4})-/);

    if (!supplierMatch) {
      throw new Error('PO number does not contain supplier information');
    }

    return supplierMatch[1];
  }

  /**
   * Generate batch of PO numbers
   */
  generateBatch(count, strategy = 'sequential') {
    if (!count || count < 0) {
      throw new Error('Count must be a positive number');
    }

    if (count > 1000) {
      throw new Error('Batch size cannot exceed 1000');
    }

    const batch = [];
    const validStrategies = ['sequential', 'dateBased', 'withChecksum'];

    if (!validStrategies.includes(strategy)) {
      throw new Error(`Invalid strategy. Must be one of: ${validStrategies.join(', ')}`);
    }

    for (let i = 0; i < count; i++) {
      if (strategy === 'sequential') {
        batch.push(this.generateSequential());
      } else if (strategy === 'dateBased') {
        batch.push(this.generateDateBased());
      } else if (strategy === 'withChecksum') {
        batch.push(this.generateWithChecksum());
      }
    }

    return batch;
  }
}

export default PONumberGenerationService;
