/* Supabase Configuration */

// Identity Project (IAM)
export const projectId = "havcomxzpyywdqtpgcgr";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhdmNvbXh6cHl5d2RxdHBnY2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0NjkxMzYsImV4cCI6MjA5NDA0NTEzNn0.B7t9VW5kD7adMQDfW9XvrdgVuYTjEDBvpAhFsBtTuKk";

// Supply Chain Project (SCM)
export const scmProjectId = "wbktqkjdsqrvqxxtitsg";
export const scmPublicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6India3Rxa2pkc3FydnF4eHRpdHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0NzQ2MTIsImV4cCI6MjA5NDA1MDYxMn0.rWnlQ2PZVAWnK5kao1GPgHHexqCquzD9XE711MWOfck";

// Fulfillment Project
export const fulfillmentProjectId = "dkqvbyewfyzfmisyisgs";
export const fulfillmentPublicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcXZieWV3Znl6Zm1pc3lpc2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MDYzODgsImV4cCI6MjA5NDA4MjM4OH0.Xui9uAuI32CENmcaqETD4QLh7TIZYslIfJuSVUwV-iU";