/**
 * ============================================================
 * Pact Provider Verification Test — SupabasePOAPI
 * ============================================================
 *
 * WHAT IS BEING TESTED:
 *   This test runs Pact's provider-side verification against the
 *   consumer contract(s) generated by the frontend (PharmaPOFrontend).
 *
 *   It loads the contract file from `pacts/PharmaPOFrontend-SupabasePOAPI.json`
 *   and replays each interaction against the real remote Supabase REST API,
 *   verifying that the provider's actual responses match the contract.
 *
 * ENVIRONMENT VARIABLES (required):
 *   PROVIDER_BASE_URL  — The Supabase REST API base URL.
 *                        Example: https://<project-id>.supabase.co
 *   SUPABASE_ANON_KEY  — The Supabase public anon key.
 *                        Used as both `apikey` header and Bearer token.
 *
 * PREREQUISITES:
 *   1. Set both environment variables before running this test.
 *   2. The pact file must exist at:
 *      pacts/PharmaPOFrontend-SupabasePOAPI.json
 *
 * USAGE:
 *   PROVIDER_BASE_URL=https://<id>.supabase.co \
 *   SUPABASE_ANON_KEY=eyJ... \
 *   npm run test:provider
 *
 * WHAT HAPPENS:
 *   - The Verifier reads the pact contract file
 *   - For each interaction, it injects the Supabase auth headers
 *     (apikey + Authorization Bearer) via `requestFilter`
 *   - It sends the request to the remote provider and compares the
 *     real response against the contract's expectations
 *   - If all interactions pass, the provider is verified
 *
 * SCRUM REFERENCE: SCRUM-S4-012-T3 — Provider Verification
 * ============================================================
 */

import path from "path";
import { describe, it, expect } from "@jest/globals";
import { Verifier } from "@pact-foundation/pact";

// ---------------------------------------------------------------------------
// Resolve the absolute path to the pact contract file.
// This is the contract generated by the consumer tests.
// ---------------------------------------------------------------------------
const pactFile = path.resolve(process.cwd(), "pacts", "PharmaPOFrontend-SupabasePOAPI.readonly.json");

// ---------------------------------------------------------------------------
// PROVIDER_BASE_URL — the remote Supabase REST API base URL.
//
// Example: https://<project-id>.supabase.co
//
// This is required because the provider is a remote Supabase instance,
// not a local server. The test will fail fast if it is not set.
// ---------------------------------------------------------------------------
const providerBaseUrl = process.env.PROVIDER_BASE_URL;
if (!providerBaseUrl) {
  throw new Error(
    "PROVIDER_BASE_URL is required.\n" +
    "Set it to your Supabase project URL, e.g.:\n" +
    "  PROVIDER_BASE_URL=https://<project-id>.supabase.co npm run test:provider"
  );
}

// ---------------------------------------------------------------------------
// SUPABASE_ANON_KEY — the public anon key for Supabase auth.
//
// Supabase requires this as both the `apikey` header and as a Bearer token
// in the `Authorization` header for all REST API requests.
// ---------------------------------------------------------------------------
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;
if (!supabaseAnonKey) {
  throw new Error(
    "SUPABASE_ANON_KEY is required.\n" +
    "Set it to your Supabase public anon key, e.g.:\n" +
    "  SUPABASE_ANON_KEY=eyJhbGciOi... npm run test:provider"
  );
}

describe("Pact Provider Verification — SupabasePOAPI", () => {
  // =========================================================================
  // TEST: Verify all consumer contract interactions against the provider
  // =========================================================================
  it("should validate the provider against the PharmaPOFrontend consumer contract", async () => {
    // -----------------------------------------------------------------------
    // Configure the Pact Verifier.
    //
    // • provider          — must match the provider name in the pact file
    // • providerBaseUrl   — the remote Supabase REST API URL
    // • pactUrls          — path(s) to the pact contract file(s)
    // • requestFilter     — injects Supabase auth headers into every request
    // • logLevel          — verbosity (debug | info | warn | error)
    // -----------------------------------------------------------------------
    const verifierOptions = {
      provider: "SupabasePOAPI",
      providerBaseUrl: providerBaseUrl,
      pactUrls: [pactFile],
      logLevel: "info",

      // -------------------------------------------------------------------
      // Request filter — injects Supabase authentication headers.
      //
      // The Pact Verifier replays each contract interaction against the
      // real provider. Supabase requires `apikey` and `Authorization`
      // headers on every request. This filter adds them automatically
      // so the contract interactions are authenticated.
      // -------------------------------------------------------------------
      requestFilter: (req, res, next) => {
        req.headers["apikey"] = supabaseAnonKey;
        req.headers["Authorization"] = `Bearer ${supabaseAnonKey}`;
        next();
      },

      // -------------------------------------------------------------------
      // State handlers.
      //
      // These callbacks run before each interaction to set up the
      // required provider state. For a remote Supabase backend, this
      // could involve seeding data via the Supabase Management API
      // or direct SQL.
      //
      // For now, they log the state being set up. Replace with real
      // setup logic when connecting to a live provider with test data.
      // -------------------------------------------------------------------
      stateHandlers: {
        "a valid Purchase Order can be created": async () => {
          console.log("[State] Setting up: a valid Purchase Order can be created");
          // TODO: Seed the database with any prerequisites for PO creation
        },
        "purchase orders with matching supplier names exist": async () => {
          console.log("[State] Setting up: purchase orders with matching supplier names exist");
          // TODO: Insert test purchase orders with supplier names containing "Test"
        },
        "a supplier scorecard exists for Test Supplier": async () => {
          console.log("[State] Setting up: a supplier scorecard exists for Test Supplier");
          // TODO: Ensure the supplier_scorecards_view has data for "Test Supplier"
        },
      },
    };

    // -----------------------------------------------------------------------
    // Run the verification.
    //
    // The Verifier replays each interaction from the pact file against
    // the remote Supabase provider and asserts that the responses conform
    // to the contract.
    //
    // This will throw (and fail the test) if any interaction does not match.
    // -----------------------------------------------------------------------
    const output = await new Verifier(verifierOptions).verifyProvider();

    // If we reach here, all interactions were verified successfully
    console.log("Provider verification complete:", output);
  });
});
